### PR TITLE
Adding in default key

### PR DESCRIPTION
**Pull request by nerdstein**
This adds in the default system key

### CODE REVIEW

**Comment by rlhawk** [comment]
The message that displays when you make a key the default is a bit confusing. 
```
Are you sure you want to make Foobar the default key?
This action cannot be undone.
```
It sounds a bit like making it the default is a permanent designation. Is there an easy way to suppress that second line?

**Comment by rlhawk** [comment]
Can Set Default be removed from the Operations list for the key that is currently the default?

**Comment by rlhawk** [comment]
Like this:
```
    if (!$entity->getServiceDefault()) {
      $operations['set_default'] = array(
        'title' => t('Set Default'),
        'weight' => -10,
        'url' => $entity->urlInfo('set-default'),
      );
    }
```

**Comment by rlhawk** [comment]
I understand that until a default has been set, we may want to encourage doing it by making it the first operation available, but once it's been set, the first operation should probably be Edit, since that's what people are most likely to want to do.

**Comment by nerdstein** [comment]
"This action cannot be undone" should be removed with the next commit

**Comment by rlhawk** [comment]
Is there any reason to allow the default key to be unset without setting a new one? If so, the operation for the default key should be "Unset default".

**Comment by rlhawk** [comment]
The logic on the getKey method is backward.

```
    if ($key_id) {
      return $this->getDefaultKey();
    } else {
      return $this->entityManager->getStorage('key')->load($key_id);
    }
```
should be
```
    if ($key_id) {
      return $this->entityManager->getStorage('key')->load($key_id);
    } else {
      return $this->getDefaultKey();
    }
```

**Comment by nerdstein** [comment]
@rlhawk - i think the question is "should there ever be a case where there is not a default". that's the unset operation. i think the answer is "no", would you agree?

**Comment by nerdstein** [comment]
I just noticed there are dupes under "Key Provider" (simple key => config, file key => file). Let me make sure this is only locally

**Comment by nerdstein** [comment]
I'm going to do a quick pass at the tests and see if they are still intact

**Comment by rlhawk** [comment]
I'm not convinced of the need for a default key, so I would leave it up to the site admin whether they want one or not.

**Comment by nerdstein** [comment]
Automated tests are good now

**Pull request merged**
