### PR TITLE
Removing default key

### PR DESCRIPTION
**Pull request by nerdstein**
1. Remove config form
2. Remove service call for default key
3. Remove routes for config form

### CODE REVIEW

**Comment by nerdstein** [comment]
@mradcliffe, @mjl3475 - code review?

Addresses issue #5

**Comment by mjl3475** [comment]
Pretty straight forward. LGTM

**Comment by nerdstein** [comment]
@mjl3475 making Travis happy... then I'll merge since you reviewed

**Comment by nerdstein** [comment]
Good to go now!

**Pull request merged**
